# Generated by Django 4.0.4 on 2022-07-04 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_projects_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
